# Generated by Django 3.0.8 on 2020-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_model', models.ImageField(upload_to='')),
                ('faceselected_model', models.ImageField(upload_to='')),
                ('faceshuffled_model', models.ImageField(upload_to='')),
            ],
        ),
    ]
