# Generated by Django 3.0.8 on 2020-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facechanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='faceselected_model',
            field=models.TextField(),
        ),
    ]
